# Generated by Django 2.2 on 2019-08-07 09:31

from django.db import migrations

def load_federation(apps, schema_editor):
    """ Creates the initial federation """
    
    Federation = apps.get_model('bartocgraphql', 'Federation')
    federation = Federation()
    federation.save() 
    
class Migration(migrations.Migration):

    dependencies = [
        ('bartocgraphql', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_federation),
    ]
