# Generated by Django 2.2 on 2019-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartocgraphql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skosmosinstance',
            name='timeout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skosmosquery',
            name='timeout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sparqlendpoint',
            name='timeout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sparqlquery',
            name='timeout',
            field=models.IntegerField(),
        ),
    ]
